# Generated by Django 6.1 on 2026-08-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('tribunal', models.CharField(default='TJRN', max_length=30)),
                ('classe', models.CharField(blank=True, max_length=150)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('partes_texto', models.TextField(blank=True)),
                ('unidade_judiciaria', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_pje', models.CharField(max_length=50, unique=True)),
                ('caixa', models.CharField(blank=True, max_length=255)),
                ('destinatario', models.CharField(blank=True, max_length=255)),
                ('tipo_documento', models.CharField(blank=True, max_length=100)),
                ('meio_comunicacao', models.CharField(blank=True, max_length=100)),
                ('data_expedicao', models.DateTimeField(blank=True, null=True)),
                ('prazo_texto', models.CharField(blank=True, max_length=100)),
                ('status_prazo_fatal', models.CharField(choices=[('calculado', 'Calculado'), ('em_calculo', 'Em cálculo'), ('sem_prazo', 'Sem prazo')], max_length=20)),
                ('prazo_fatal', models.DateTimeField(blank=True, null=True)),
                ('ciencia_texto', models.TextField(blank=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='expedientes.processo')),
            ],
        ),
    ]
