# Generated by Django 6.1 on 2026-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='acao_pje',
            field=models.CharField(blank=True, choices=[('tomar_ciencia', 'Tomar ciência'), ('sem_interesse', 'Sem interesse')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='capturado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_pendencia',
            field=models.CharField(blank=True, choices=[('ciencia', 'Pendente de ciência'), ('resposta', 'Pendente de resposta'), ('nao_identificada', 'Não identificada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
