"use client";

import { CheckCircle, Clock, FloppyDisk, Key, ShieldCheck, UserCircle } from "@phosphor-icons/react";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../components/app-shell";
import { BezelCard, Feedback, PageTitle } from "../components/ui";
import { api } from "../lib/api";
import { useAuth } from "../providers";

type Settings = { display_name: string; theme: "light" | "dark" | "system"; collection_time: string; timezone: string; credential_status: Record<string, boolean | string> };
type Source = { code: string; system: string; tribunal: string; enabled: boolean };
const fieldClass = "control mt-2 w-full px-3 py-2 text-sm font-semibold";

export default function SettingsPage() {
  const { refresh } = useAuth(); const [data, setData] = useState<Settings | null>(null); const [sources, setSources] = useState<Source[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = () => Promise.all([api<Settings>("settings/"), api<Source[]>("sources/")]).then(([settings, items]) => { setData(settings); setSources(items); }).catch((exception) => setError(exception.message));
  useEffect(() => { queueMicrotask(() => { void load(); }); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const value = await api<Settings>("settings/", { method: "PATCH", body: JSON.stringify({ display_name: form.get("display_name"), theme: form.get("theme"), collection_time: form.get("collection_time") }) }); setData(value); await refresh(); setMessage("Configurações salvas."); setError(""); } catch (exception) { setError(exception instanceof Error ? exception.message : "Falha ao salvar."); } };
  const changePassword = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get("new_password") !== form.get("confirmation")) { setError("A confirmação da nova senha não coincide."); return; } try { await api("auth/password/", { method: "POST", body: JSON.stringify({ current_password: form.get("current_password"), new_password: form.get("new_password") }) }); event.currentTarget.reset(); setMessage("Senha alterada com sucesso."); setError(""); } catch (exception) { setError(exception instanceof Error ? exception.message : "Falha ao alterar senha."); } };
  const toggle = async (source: Source) => { try { const next = await api<Source>(`sources/${source.code}/`, { method: "PATCH", body: JSON.stringify({ enabled: !source.enabled }) }); setSources((values) => values.map((item) => item.code === next.code ? next : item)); } catch (exception) { setError(exception instanceof Error ? exception.message : "Falha ao atualizar fonte."); } };
  return <AppShell><PageTitle eyebrow="Preferências e integração" title="Configurações" description="Ajuste seu ambiente e confira se a automação está preparada para coletar." />
    {error && <Feedback>{error}</Feedback>}{message && <Feedback tone="success">{message}</Feedback>}
    {data && <form onSubmit={save} className="grid gap-5 lg:grid-cols-2"><BezelCard innerClassName="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><UserCircle size={21} weight="duotone" /></span><div><h2 className="mb-1 text-sm font-extrabold text-ink">Seu perfil</h2><p className="mb-0 text-xs text-quiet">Informações exibidas no painel.</p></div></div><label className="block text-xs font-extrabold text-ink-soft">Nome de exibição<input className={fieldClass} name="display_name" defaultValue={data.display_name} /></label><label className="mt-4 block text-xs font-extrabold text-ink-soft">Tema<select className={fieldClass} name="theme" defaultValue={data.theme}><option value="light">Claro</option><option value="dark">Escuro</option><option value="system">Seguir o sistema</option></select></label></BezelCard><BezelCard innerClassName="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-info-soft text-info"><Clock size={21} weight="duotone" /></span><div><h2 className="mb-1 text-sm font-extrabold text-ink">Coleta diária</h2><p className="mb-0 text-xs text-quiet">Agende a rotina automática de coleta.</p></div></div><label className="block text-xs font-extrabold text-ink-soft">Horário<input className={fieldClass} name="collection_time" type="time" defaultValue={data.collection_time} /></label><label className="mt-4 block text-xs font-extrabold text-ink-soft">Fuso horário<input className={fieldClass} value="America/Fortaleza" disabled /></label></BezelCard><div className="flex justify-end lg:col-span-2"><button className="button-primary cursor-pointer px-4 text-sm"><FloppyDisk size={17} weight="bold" />Salvar alterações</button></div></form>}
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><BezelCard innerClassName="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><ShieldCheck size={21} weight="duotone" /></span><div><h2 className="mb-1 text-sm font-extrabold text-ink">Fontes conectadas</h2><p className="mb-0 text-xs text-quiet">Desativar uma fonte preserva seu histórico.</p></div></div><div className="space-y-2">{sources.map((source) => <div className="flex items-center gap-3 rounded-xl border border-rule bg-panel-muted/60 p-3" key={source.code}><span className="grid size-9 place-items-center rounded-lg bg-brand-soft text-xs font-extrabold text-brand">PJe</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm text-ink">{source.system}</strong><small className="text-xs text-quiet">{source.tribunal} · Expedientes</small></div><button role="switch" aria-label={`Coleta ${source.system} ${source.tribunal}`} aria-checked={source.enabled} className={`relative h-6 w-11 cursor-pointer rounded-full border-0 p-1 transition-colors ${source.enabled ? "bg-brand" : "bg-quiet/40"}`} onClick={() => toggle(source)}><i className={`block size-4 rounded-full bg-white shadow-sm transition-transform ${source.enabled ? "translate-x-5" : ""}`} /></button></div>)}</div></BezelCard>
      {data && <BezelCard innerClassName="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-positive-soft text-positive"><CheckCircle size={21} weight="duotone" /></span><div><h2 className="mb-1 text-sm font-extrabold text-ink">Prontidão do PJe</h2><p className="mb-0 text-xs text-quiet">Valores sensíveis não são expostos aqui.</p></div></div><div className="space-y-2"><Check ok={Boolean(data.credential_status.credential_file)} label="Arquivo de credenciais" /><Check ok={Boolean(data.credential_status.pin)} label="PIN do certificado" /><Check ok={Boolean(data.credential_status.totp)} label="Segredo TOTP" /><Check ok label="PJeOffice" note="Verificado durante cada coleta" /><code className="mt-2 block rounded-xl bg-panel-muted p-3 text-xs text-quiet">~/.config/pje-automacao/.env</code></div></BezelCard>}</div>
    <form onSubmit={changePassword} className="mt-5"><BezelCard innerClassName="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-caution-soft text-caution"><Key size={21} weight="duotone" /></span><div><h2 className="mb-1 text-sm font-extrabold text-ink">Senha de acesso</h2><p className="mb-0 text-xs text-quiet">Altere a senha usada somente nesta instalação local.</p></div></div><div className="grid gap-3 md:grid-cols-4"><label className="text-xs font-extrabold text-ink-soft">Senha atual<input className={fieldClass} name="current_password" type="password" autoComplete="current-password" required /></label><label className="text-xs font-extrabold text-ink-soft">Nova senha<input className={fieldClass} name="new_password" type="password" minLength={8} autoComplete="new-password" required /></label><label className="text-xs font-extrabold text-ink-soft">Confirmar senha<input className={fieldClass} name="confirmation" type="password" minLength={8} autoComplete="new-password" required /></label><button className="button-secondary mt-[22px] cursor-pointer px-4 text-sm">Alterar senha</button></div></BezelCard></form>
  </AppShell>;
}
function Check({ ok, label, note }: { ok: boolean; label: string; note?: string }) { return <div className="flex items-center gap-3 rounded-xl border border-rule bg-panel-muted/60 p-3"><span className={`grid size-7 place-items-center rounded-full ${ok ? "bg-positive-soft text-positive" : "bg-caution-soft text-caution"}`}>{ok ? "✓" : "!"}</span><div><strong className="block text-xs text-ink">{label}</strong><small className="text-[11px] text-quiet">{note ?? (ok ? "Configurado" : "Configuração ausente")}</small></div></div>; }
