# Generated by Django 6.1.1 on 2026-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_automationrun_cycle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrun',
            name='trigger',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('manual', 'Manual'), ('rerun', 'Reexecução de fonte'), ('catch_up', 'Recuperação')], default='manual', max_length=20),
        ),
    ]
