# Generated by Django 6.1.1 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0012_alter_automationrun_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrun",
            name="descartada_em",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
